In [1]:
import numpy as np

A = [[4,1], # The matrix is symmetric due to which the eigen values and singular values are same
     [1,3]]
eigenvalues, _ = np.linalg.eig(A)
print("Eigenvalues:\n", eigenvalues)
singular_values = np.linalg.svd(A, compute_uv=False)
print("Singular values:\n", singular_values)
U, _, Vt = np.linalg.svd(A)
print("U matrix:\n", U)
print("V transpose matrix:\n", Vt)

Eigenvalues:
 [4.61803399 2.38196601]
Singular values:
 [4.61803399 2.38196601]
U matrix:
 [[-0.85065081 -0.52573111]
 [-0.52573111  0.85065081]]
V transpose matrix:
 [[-0.85065081 -0.52573111]
 [-0.52573111  0.85065081]]


In [9]:
B = [[1,2],
     [2,3],
     [3,4]]
U_B, sigma_B, Vt_B = np.linalg.svd(B)
print("U matrix for B:\n", U_B)
print("Sigma values for B:\n", sigma_B)
print("V transpose matrix for B:\n", Vt_B)

U matrix for B:
 [[-0.33809817  0.84795222  0.40824829]
 [-0.55064932  0.17354729 -0.81649658]
 [-0.76320047 -0.50085764  0.40824829]]
Sigma values for B:
 [6.54675564 0.37415323]
V transpose matrix for B:
 [[-0.56959484 -0.82192562]
 [-0.82192562  0.56959484]]


In [10]:
C = np.random.randint(1, 10, (5, 3))
print("New C matrix:\n", C)
U_C, sigma_C, Vt_C = np.linalg.svd(C)
print("U matrix for C:\n", U_C)
print("Sigma values for C:\n", sigma_C)
print("V transpose matrix for C:\n", Vt_C)

# Reduced SVD
U_C_reduced = U_C[:, :2]
sigma_C_reduced = np.diag(sigma_C[:2])
Vt_C_reduced = Vt_C[:2, :]
print("Reduced U matrix for C:\n", U_C_reduced)
print("Reduced Sigma values for C:\n", sigma_C_reduced)
print("Reduced V transpose matrix for C:\n", Vt_C_reduced)

New C matrix:
 [[1 3 8]
 [9 4 1]
 [9 5 1]
 [2 5 9]
 [5 2 6]]
U matrix for C:
 [[-0.37285873 -0.49098676  0.021337   -0.61204634 -0.4948256 ]
 [-0.45522338  0.50083326  0.06464975  0.38326108 -0.62519523]
 [-0.48103309  0.5041464  -0.32559971 -0.47151119  0.43139959]
 [-0.4924687  -0.49273154 -0.46456732  0.49955517  0.22206315]
 [-0.42406342 -0.10559398  0.82068701  0.08143739  0.35897201]]
Sigma values for C:
 [18.31237092 10.65672734  2.25637622]
V transpose matrix for C:
 [[-0.65007538 -0.47263708 -0.5949926 ]
 [ 0.66065284  0.03530719 -0.74986081]
 [ 0.37541954 -0.8805496   0.28929669]]
Reduced U matrix for C:
 [[-0.37285873 -0.49098676]
 [-0.45522338  0.50083326]
 [-0.48103309  0.5041464 ]
 [-0.4924687  -0.49273154]
 [-0.42406342 -0.10559398]]
Reduced Sigma values for C:
 [[18.31237092  0.        ]
 [ 0.         10.65672734]]
Reduced V transpose matrix for C:
 [[-0.65007538 -0.47263708 -0.5949926 ]
 [ 0.66065284  0.03530719 -0.74986081]]


In [12]:
# Given singular values
singular_values = np.array([10, 8, 0.1, 0.05, 0.001])

# Create a random 5x5 matrix
D = np.random.rand(5, 5)

# Perform SVD
U_D, sigma_D, Vt_D = np.linalg.svd(D)

# Keep only the top 2 singular values and corresponding vectors
U_D_reduced = U_D[:, :2]
sigma_D_reduced = np.diag(singular_values[:2])
Vt_D_reduced = Vt_D[:2, :]

# Rank 2 approximation
D_rank_2 = U_D_reduced @ sigma_D_reduced @ Vt_D_reduced

print("Rank 2 approximation of the matrix:\n", D_rank_2)

Rank 2 approximation of the matrix:
 [[ 3.09471053  3.62876749 -0.80826106 -0.07215697  2.35241056]
 [-0.13141818 -0.56199877  5.48725285  5.23982404  0.94979324]
 [ 2.24705556  2.46111173  1.73545987  2.17787775  2.15512443]
 [ 3.51774329  4.06498651 -0.11909978  0.68592607  2.8279064 ]
 [ 1.3177225   1.36362727  2.0821241   2.29937123  1.46871156]]
